# Standorte der Schulweghelfer.
# "id" wird in der Datenbank gespeichert und darf später nicht mehr geändert werden.
# "name" ist nur die Anzeige und kann jederzeit angepasst werden.
title: Schulweghelferlein

locations:
  - id: standort-1
    name: Aschheimer Str.
  - id: standort-2
    name: Hohenlindner Str. B471
  - id: standort-3
    name: Hohenlindner/Bodmer Str.
  - id: standort-4
    name: Bahnhofstr.
  - id: standort-5
    name: Zeppelinstr.
  - id: standort-6
    name: Dornacherstr.
  - id: standort-7
    name: Emeranstr.
